advantage_normalization: true
batch_size: 128
batch_size_vf: 128
clip_range:
    init: 0.2
    final: 0
    ftype: "linear"
ent_coef: 0.0
full_action: false
kl_coef: 0.0
vf_coef: 0.5
learning_rate:
    init: 0.00025
    final: 0
    ftype: "linear"
n_epochs: 10
n_epochs_vf: 10
n_steps: 128
shared: true
nenvs: 64
nheads: 4