advantage_normalization: true
batch_size: 64
batch_size_vf: 64
clip_range:
    init: 0.2
    final: 0
    ftype: "linear"
ent_coef: 0.0
full_action: false
gae_like_lambda: 0.0
use_sub_action_ratio: true
dae_discouple_correction: false
kl_coef: 0.0
vf_coef: 0.5
learning_rate:
    init: 0.00025
    final: 0
    ftype: "linear"
learning_rate_vf: 0.00015
n_epochs: 10
n_epochs_vf: 6
n_steps: 32
shared: false
nenvs: 8
nheads: 4