advantage_normalization: true
batch_size: 4096
batch_size_vf: 4096
ent_coef: 0.0
full_action: false
dae_discouple_correction: false
kl_coef: 0.0
vf_coef: 0.5
learning_rate:
    init: 0.00025
    final: 0
    ftype: "linear"
n_epochs: 6
n_epochs_vf: 10
n_steps: 128
shared: true
nenvs: 32
nheads: 1