advantage_normalization: true
batch_size: 1024
batch_size_vf: 1024
clip_range:
    init: 0.2
    final: 0
    ftype: "linear"
ent_coef: 0.0
full_action: false
kl_coef: 0.0
vf_coef: 0.5
learning_rate:
    init: 0.00025
    final: 0
    ftype: "linear"
n_epochs: 10
n_epochs_vf: 10
n_steps: 32
shared: true
nenvs: 1024