batch_size: 4096
vf_coef: 0.5
ent_coef: 0.0
clip_range:
    init: 0.2
    final: 0
    ftype: "linear"
clip_range_vf: 0.2
learning_rate:
    init: 0.00015
    final: 0
    ftype: "linear"
n_epochs: 10
n_steps: 128
nenvs: 32
